// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_EcAxB3kNoXW2Awr8h9YXSFIiJXmN4NI',
    appId: '1:1049862105791:web:64d447008a6ef9262d340a',
    messagingSenderId: '1049862105791',
    projectId: 'wheelsdeals-b19a3',
    authDomain: 'wheelsdeals-b19a3.firebaseapp.com',
    storageBucket: 'wheelsdeals-b19a3.appspot.com',
    measurementId: 'G-GYRNYW45G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcynB3rMcPJ7uMpmGX9qzHioUtYcqO42U',
    appId: '1:1049862105791:android:ade9e2a633b38c7b2d340a',
    messagingSenderId: '1049862105791',
    projectId: 'wheelsdeals-b19a3',
    storageBucket: 'wheelsdeals-b19a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDvzsW3wxbDAy7uOvQYUjXBXZD58ObQBc',
    appId: '1:1049862105791:ios:b3d3c776f48a76572d340a',
    messagingSenderId: '1049862105791',
    projectId: 'wheelsdeals-b19a3',
    storageBucket: 'wheelsdeals-b19a3.appspot.com',
    iosClientId: '1049862105791-35r1od9vi9ndrdb3ajarphmt4o1jrgfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheelsDeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDvzsW3wxbDAy7uOvQYUjXBXZD58ObQBc',
    appId: '1:1049862105791:ios:b3d3c776f48a76572d340a',
    messagingSenderId: '1049862105791',
    projectId: 'wheelsdeals-b19a3',
    storageBucket: 'wheelsdeals-b19a3.appspot.com',
    iosClientId: '1049862105791-35r1od9vi9ndrdb3ajarphmt4o1jrgfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheelsDeals',
  );
}
